temp

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -21,7 +21,8 @@ jobs:
         run: uname -a   
       
       - name: Test npm-install-action
-        run: ${{ command -v apt-get >/dev/null && then sudo DEBIAN_FRONTEND=noninteractive apt-get install -qq -o=Dpkg::Use-Pty=0 rdfind || command -v yum >/dev/null && sudo amazon-linux-extras epel -y &&  sudo yum install rdfind -y || echo "Cannot find an installer." }}
+        run: |
+          temp=`command -v apt-get >/dev/null && then sudo DEBIAN_FRONTEND=noninteractive apt-get install -qq -o=Dpkg::Use-Pty=0 rdfind || command -v yum >/dev/null && sudo amazon-linux-extras epel -y &&  sudo yum install rdfind -y || echo "Cannot find an installer."`
         
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
